data:
  data_path: 'data/processed/requirements_mc2.csv'
  min_count: 2

model:
  neg_samples: 5
  embed_dim: 100

training:
  epochs: 20
  learning_rate: 0.005
  batch_size: 1000
  optimizer: 'SparseAdam'

output:
  path: 'skipgram_results/'
